alias ll='ls -AlF'
alias la='ls -A'
alias l='ls -CF'
alias ..="cd .."
alias ...="cd ../../"
alias octave="octave --no-gui -q"
alias bc="bc -q"
alias caio-update="sudo apt-get update && sudo apt-get -y upgrade"
alias caio-refresh="sudo apt-get -y autoremove && sudo apt-get -y autoclean && sudo apt-get -y clean"